### ISSUE TITLE
JSPM exports?

### ISSUE THREAD

**Issue by mfredix** [DataTables/DataTables#564]
Tried to use DataTables with JSPM, but ran into the following issue: if you set up a dependency on datatables, you get the jquery object. But is seems like the intention is to export $.fn.dataTable. E.g. the Bootstrap integration uses 

    define( ['jquery', 'datatables'], factory );
where 

    var factory = function( $, DataTable ) {...}
and this fails if you load the code with SystemJS. I am new to both JSPM and DataTables so this is a bit fuzzy, but I noticed that the package.json has a jspm entry with a shim exporting $, could be the cause. I guess this will not be noticed in many cases, but combined with a third module, like the bootstrap integration, you will likely get an error.

**Comment by DataTables** [comment]
I'm going to send up the bat signal as ask for @guybedford 's help with this one!

DataTables fundamentally requires jQuery which is why it has a dependency on it. But it sounds like you are getting two jQuery's?

Can you link to a page showing the result from your build, and what modules you are using to built your page please?

**Comment by mfredix** [comment]
Don't think the issue is with jQuery, that part looks good. I don't have a public page to show, but the steps to reproduce are straightforward: install jspm, use jspm to install jquery and DataTables. Create a js file "mymodule.js" with a module that uses datatables:

    define(["require", "exports", 'datatables'], function (require, exports, dt) {
        // The question is what should you expect dt to be?
    });
Load the module on a page the SystemJS way:

     <script>
        System.import('mymodule');
    </script> 
It turns out that dt is actually $. But if you look at how dataTables.bootstrap.js is written it expects the dataTable to be exported, so you get an error (it is when the you get to 

    /* Default class modification */
    $.extend( DataTable.ext.classes, { 
        // Goes wrong, since DataTable is actually $ here
    });

in dataTables.bootstrap.js). I think what happens is that JSPM forces $ to be exported, breaking the bootstrap integration, but it is just my guess.

**Comment by guybedford** [comment]
@mfredix are you suggesting that the module value for DataTables should be the plugin value instead of jQuery itself? If so, @DataTables this can be done via setting `"exports": "$.fn.dataTable"` at https://github.com/DataTables/DataTables/blob/master/package.json#L47.

**Comment by mfredix** [comment]
@guybedford Yes, exactly. Or: if the best practice for JQuery plugins is to use jQuery itself as module value, then the bootstrap integration should be updated.

**Comment by cosminonea** [comment]
I think this problem is back in the code since 1.10.10, but slightly different.

When requiring datatables from a module like below I get a dataTable is not a function. The same code works with 1.10.9.

```
import $ from 'jquery';
import {dataTable} from 'datatables.net';

export class SimpleTable {
    constructor() {
        $('#data').dataTable({
            "fixedColumns": true,
            "fixedHeader": true,
            "responsive": false,
            "scrollY": 400,
            "scrollX": true,
            "autoFill": false,
            "select": false,
            "processing": true,
            "scrollCollapse": true,
            "paging": false
        });
    }
}
```

Stepping through the code it seems that the `factory($, root, root.document)` is never executed and the plugin does not get installed.

**Comment by DataTables** [comment]
The CommonJS loader in DataTables 1.10.10+ returns an object that must be executed to attach DataTables to a jQuery and / or window instance (optionally - but it must be executed).

In [npm you can do](//datatables.net/download/npm):

```
dt = require( 'datatables.net-dt' )();
```

In ES6 you would do something like:

```js
import {dataTable} from 'datatables.net';

dataTable();
// or dataTable( window, $ );
```

I don't think you can execute a module return immediately like you can with `require` statements, but happy to be wrong there!

I've mentioned this in a couple of other places, but sorry! The chance in the loader should have been a major version changed rather than a patch - it was only once it was out that I realised all of the implications for existing loaders.

**Comment by cosminonea** [comment]
```
import $ from 'jquery';
import {dataTable} from 'datatables.net';

dataTable();
```
dataTable is undefined when I execute this.

**Comment by cosminonea** [comment]
This works though:

```
import $ from 'jquery';
import * as dataTable from 'datatables.net';

dataTable.default(window, $);
```

**Comment by DataTables** [comment]
Ah yes. DataTables doesn't export a default as it doesn't implement ES6 modules in its UMD yet (waiting for support in one or more of the browser engines before introducing that).

I would have thought that whatever transpiler you are using would use the default automatically though.

**Comment by cosminonea** [comment]
I am trying to use it in an Aurelia JS app using JSPM/SystemJS v0.19.6 with Babel.

**Comment by guybedford** [comment]
The import here should always be `import dataTabel from 'datatables.net'` for the above to work surely?

**Comment by vaskokj** [comment]
@cosminonea Are you able to get this example to work in Aurelia? I can't. 

https://datatables.net/extensions/responsive/examples/styling/bootstrap.html

**Comment by jsobell** [comment]
The simplest way in jspm seems to be
```
System.import('datatables.net').then(jq => jq());
```
You can load plugins the same way:
```
System.import('datatables.net')
  .then((jq) => { jq(); return System.import('./modules/ellipses')});
```

**Comment by cjkoski** [comment]
This was how I did mine inside the file doing System.import:

import $ from 'jquery3-1-1';

import dataTable from 'datatables.net';
dataTable(window, $);  //attaches to global jquery object

//plugin
import selectDataTables from 'datatables.net-select';
selectDataTables(window, $);
